### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by huang8023wei** [Rukey7/MvpApp#4]
Process: com.dl7.mvp, PID: 16829
                                                             java.lang.RuntimeException: Unable to destroy activity {com.dl7.mvp/com.dl7.mvp.module.photo.bigphoto.BigPhotoActivity}: java.lang.NullPointerException
                                                                 at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3521)
                                                                 at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3539)
                                                                 at android.app.ActivityThread.access$1400(ActivityThread.java:135)
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1249)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                 at android.os.Looper.loop(Looper.java:136)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5045)
                                                                 at java.lang.reflect.Method.invokeNative(Native Method)
                                                                 at java.lang.reflect.Method.invoke(Method.java:515)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                                 at dalvik.system.NativeStart.main(Native Method)
                                                              Caused by: java.lang.NullPointerException

点击美女图片的时候报错了

**Comment by Rukey7** [comment]
空指针没具体到代码中哪一行吗，我前面改了一个图片界面报错问题，你要不再试试新的代码

**Comment by ytl2009** [comment]
不能正常运行，有很多烦类找不到，如：
![image](https://cloud.githubusercontent.com/assets/14970665/23838766/fd5029b0-07d3-11e7-814a-ebd62887321f.png)
